package com.majeur.psclient.model.battle

/**
 * In-memory model of the move-animation data bundled in
 * `res/raw/battle_animations.json` (generated by
 * `build-tools/build_battle_animations.py` from the Pokémon Showdown client).
 *
 * The JSON is namespaced into three sections:
 *  - [moves]  : per-move animations (key = move id, e.g. "flamethrower")
 *  - [other]  : shared BattleOtherAnims (key = anim name, e.g. "contactattack")
 *  - [status] : shared BattleStatusAnims (key = anim name, e.g. "flinch")
 *
 * A move whose only call is an [OtherAnim] delegates to the matching entry in
 * [other]; the delegation is resolved at runtime.
 *
 * Licensing: the "moves" data is CC0-1.0; "other"/"status" are MIT (Pokémon
 * Showdown). See the repo-root NOTICE file.
 */
class AnimSequence(
    val anim: List<AnimCall>,
    val prepareAnim: List<AnimCall>,
    val residualAnim: List<AnimCall>,
)

/** A single recorded animation instruction. */
sealed class AnimCall

/**
 * Spawn a transient particle/sprite and tween it from [start] to [end].
 *
 * [effect] is one of:
 *  - an fx/ particle basename (e.g. "fireball") -> load from /fx/{effect}.png
 *  - "{attacker}" / "{defender}" -> use that participant's own Pokémon sprite
 *  - a full "https://..." URL -> a custom remote sprite
 *
 * [after] is an optional post-effect hint from the source ("fade", "explode"…).
 */
class ShowEffect(
    val effect: String,
    val start: AnimPos?,
    val end: AnimPos?,
    val transition: String?,
    val after: String?,
) : AnimCall()

/** Tween a participant's own Pokémon sprite to [pos]. [sprite] is "attacker" or "defender". */
class SpriteAnim(
    val sprite: String,
    val pos: AnimPos,
    val transition: String?,
) : AnimCall()

/** Insert [time] ms of idle time into a participant sprite's animation queue. */
class SpriteDelay(
    val sprite: String,
    val time: Int,
) : AnimCall()

/** Flash the battle background. [color] may be null (default flash). */
class BackgroundEffect(
    val color: String?,
    val time: Int,
    val opacity: Float?,
    val delay: Int,
) : AnimCall()

/** Advance the scene timeline by [time] ms before scheduling subsequent calls. */
class Wait(
    val time: Int,
) : AnimCall()

/** Delegate to a named entry in the [BattleAnims.other] table (e.g. "contactattack"). */
class OtherAnim(
    val name: String,
) : AnimCall()

/**
 * A scene-space keyframe. All fields are optional; absent fields fall back to
 * the engine defaults (x=y=z=0, scale=xscale=yscale=1, opacity=1).
 * [time] is the tween duration in ms for this keyframe.
 */
class AnimPos(
    val x: AnimCoord?,
    val y: AnimCoord?,
    val z: AnimCoord?,
    val scale: Float?,
    val xscale: Float?,
    val yscale: Float?,
    val opacity: Float?,
    val time: Int?,
)

/**
 * A single x/y/z coordinate, either:
 *  - relative: [rel] = "attacker"|"defender", [axis] = "x"|"y"|"z", and [value]
 *    is the offset added to that participant's scene coordinate on [axis].
 *  - absolute: [rel] and [axis] are null and [value] is the literal scene value.
 */
class AnimCoord(
    val rel: String?,
    val axis: String?,
    val value: Float,
) {
    val isRelative get() = rel != null
}
